### ISSUE TITLE
Content: Modern Application Development - Development Rhythm Workshop

### ISSUE THREAD

**Issue by billkable** [vmware-tanzu/tanzu-dev-portal#1098]
## Summary of content

The foundation article is the fifth lesson in the [Modern Application Development Rhythm Course](https://github.com/vmware-tanzu/tanzu-dev-portal/issues/1039).

As a developer, I need to demonstrate how the following are used in a developer flow:

- Application of development principles, such a one of the SOLID principles
- Application of development practices, such as TDD and Refactoring, using Red/Green/Refactor techniques

## Summary of audiences

Include:

- The primary audience includes developers new to modern application practices.
- The secondary audience include other Team roles for understanding of the modern application development workflow

It is assumed developers have at least a minimum level of development proficiency in either an object-oriented or functional language.

This series is also a primer for developers that will pair with engineers on Tanzu Labs engagements.

## Level of content

Level of content as it pertains to the topic proposed will be at a 100 "Awareness/Exploration" level.

## Tasks

- [x] 101: Build codebase
- [x] 102: Intro
- [x] 103: Backlog
- [x] 104: Codebase
- [x] 105: Implement new feature
- [x] 106: Curate your commit
- [x] 107: Integrate your work
- [x] 108: Wrap
- [x] 109: need image updates
